# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkID=512686

name: Microsoft C++ Code Analysis

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.mdb
      - build/*.props
      - build/*.ps1
      - build/*.xml
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.mdb
      - build/*.props
      - build/*.ps1
      - build/*.xml
  schedule:
    - cron: '31 18 * * 5'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -B out -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON

      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@24c285ab36952c9e9182f4b78dfafbac38a7e5ee # v0.1.1
        id: run-analysis
        with:
          cmakeBuildDirectory: ./out
          buildConfiguration: Debug
          ruleset: NativeRecommendedRules.ruleset

      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@9e907b5e64f6b83e7804b09294d44122997950d6 # v3.29.5
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
